lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug RumblWeb.RequireAuth
  end

  # Unauthenticated Pages
  scope "/", RumblWeb do
    pipe_through :browser
    resources "/users", UserController, only: [:new, :create]

    get  "/log_in", SessionController, :new
    post "/log_in", SessionController, :create
    post "/log_out", SessionController, :delete

    get "/", PageController, :index
  end

  # Authenticated Pages
  scope "/", RumblWeb do
    pipe_through [:browser, :auth]

    resources "/users", UserController, only: [:index, :show]
    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl_web/views/layout_view.ex
defmodule RumblWeb.LayoutView do
  use RumblWeb, :view
end

lib/rumbl_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Rumbl!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <section class="container">
          <nav role="navigation">
            <ul>
              <%= if @current_user do %>
                <li><%= @current_user.username %></li>
                <li><%= link "Log out", to: Routes.session_path(@conn, :delete), method: "post" %></li>
              <% else %>
                <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
                <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
              <% end %>
            </ul>
          </nav>
          <a href="http://phoenixframework.org/" class="phx-logo">
            <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
          </a>
        </section>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>